{% set version = "0.13.1" %}

package:
  name: nipype
  version: {{ version }}

source:
  fn: nipype-fix-configparser.zip
  url: https://github.com/satra/nipype/archive/fix/configparser.zip
  md5: eb5efa84420e429b9b62700407a1aa09

build:
  number: 0
  script:
    - rm requirements.txt
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - future >=0.16.0
    - configparser  # [py27 or py34]
    - pywin32  # [win]

  run:
    - python
    - nibabel >=2.1.0
    - networkx >=1.7
    - numpy >=1.6.2
    - python-dateutil >=1.5
    - scipy >=0.11
    - traits >=4.6
    - future >=0.16.0
    - simplejson >=3.8.0
    - prov >=1.5.0
    - click >=6.6.0
    - funcsigs
    - configparser  # [py27 or py34]
    - pytest >=3.0
    - mock 
    - pydotplus
    - xvfbwrapper
    - psutil
    - matplotlib
    - pywin32  # [win]

test:
  # Python imports
  imports:
    - nipype

about:
  home: https://github.com/nipy/nipype
  license: Apache 2.0
  summary: 'Nipype, an open-source, community-developed initiative under the
  umbrella of NiPy, is a Python project that provides a uniform interface to
  existing neuroimaging software and facilitates interaction between these
  packages within a single workflow. Nipype provides an environment that
  encourages interactive exploration of algorithms from different packages
  (e.g., SPM, FSL, FreeSurfer, AFNI, Slicer, ANTS), eases the design of
  workflows within and between packages, and reduces the learning curve
  necessary to use different packages. Nipype is creating a collaborative
  platform for neuroimaging software development in a high-level language and
  addressing limitations of existing pipeline systems.'

extra:
  recipe-maintainers:
    - chrisfilo
    - satra
