{% set version = "1.9.2" %}
{% set name = "nipype" %}
{% set sha256 = "c484d6d1ba99d8c2e641bcd611614ed57c33c6cb33ff78bfbe3b2be4474a16fd" %}
{% set python_min = "3.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pywin32-on-windows

  run:
    - python >={{ python_min }}
    - nibabel >=3.0.0
    - networkx >=2.5
    - numpy >=1.21
    - python-dateutil >=2.2
    - scipy >=1.8
    - traits >=6.2
    - simplejson >=3.8.0
    - rdflib >=5.0.0
    - prov >=1.5.2
    - click >=6.6.0
    - pydot >=1.2.3
    - xvfbwrapper
    - psutil >=5.0
    - pywin32-on-windows
    - packaging
    - filelock >=3.0.0
    - acres
    - etelemetry >=0.3.1
    - looseversion
    - puremagic

test:
  requires:
    - python {{ python_min }}
  imports:
    - nipype

about:
  home: https://github.com/nipy/nipype
  license: Apache-2.0
  license_file: LICENSE
  summary: Nipype, an open-source, community-developed initiative under the umbrella of NiPy, is a Python project that provides a uniform interface to existing neuroimaging software and facilitates interaction between these packages within a single workflow. Nipype provides an environment that encourages interactive exploration
    of algorithms from different packages (e.g., SPM, FSL, FreeSurfer, AFNI, Slicer, ANTS), eases the design of workflows within and between packages, and reduces the learning curve necessary to use different packages. Nipype is creating a collaborative platform for neuroimaging software development in a high-level language
    and addressing limitations of existing pipeline systems.

extra:
  recipe-maintainers:
    - chrisgorgo
    - satra
    - mgxd
    - effigies
