appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZXSB0I0JkNCyUbg54TFy9vumUC6dy9simsOXIPQpKlVLZL7JZTdoADgxH2rwK0ZbGhg6Yb7cQx78+MZ/HHTlDBoSd2cX/SD9xz8wDaLo9wQ7wXRzl1vf8vx9nSkxranl2EYRfZbQZQtPZrnelxp8PDF9pKv622mKyQ2JaVef+bme1I+vX3uI0L6niQUjSxUuyxoXjxg+xt8PWfP1yVjC17rVRs089FMKYFiB7dxKmQGiiCdjTAGyymNiffGpg4rCNVdoBBbpUZSu2oR3I9j68oYZN3OuHuaSwMUs4dO7SAj/oQffsjxKfCd8nzqOpakeCT8AE34tbGlY/sScuA2qub7ciwsXhE2qKJYD5LzizBztTdMsFr+cMppOkiFeropEWdqBAryEApBwBm1UTmArArYKHyQ13BH6MWuAL0FI+QFIwV9g6fzFFOaf4rbFIZ994mVm1CAXLFi8Tt1cbl3Rvl447vrMLZPleQGZ+i4sTJDU3rrqQubDuBaSa5O1bBjNaUCLnR4KopWZj8vX71s1kEk2vSmnu8lElarV5ur1I8KhAoMURp1JDyym5DBMwbO1Y08LQWZ+6BmolaDh6CE6udxHY1aSU5OBCZ85Omcya7Bo7lh9Vn8VLrPAVktsivxOrIfAJSFI0/+QqsAXChW33jkWsb8kExI/7qyF+giC7r0=}
