travis:
  secure:
    BINSTAR_TOKEN: ZeAo+YJLUq2IX1pWGkVOrnzEF6EHWQIWtK9R1ugW9KSx6CZGMAwSdP7zJYpHWHtKDZ5afgK23+hgSJDLx0cNyWHD4s10Mm2PrIdhtctOFIpMHhujJ+q8VEusjucLP/whWfSWJYARbkDUdFXA4T9X47EJYyTSdhPebMuvFRDXH16idqxT1oUlJv4WdYDdsyUWLjiYKMdeS5HO6EoDZJl/diDlHvNZzl/6tOR8TCuHThwtDpVKj6CsMLSRGhrxuwlb3futqLwfvq5/9mz/JpWO2Ba2rGjrSPDIM5VEy6LEXxIAo9tCvN6FgGR3L44gUbat6voJ70E8XyzHsbwDKrlZ0ZMHgl81WcuikLvsMg8ak7NLpOm9cMyA4o0MsxgoDTFbp6mtLrmVy1crxgqr5ukd5AMHLoiJPPvUtsHbgKz/XnXbqqo007R1a9qtCTK66735CcDkoBBXDHBdSBzAW4PwTNSw7feIks7t4mX0VL2vEjTahnMI1NUzMV7J6zgKEubd9Z4TeyxWSHzzZM/TzhZTIoJipP3ZhkE3bvv6nBvCSMrjFcQd9ty1Oon2sOMdCjUrxrrLwAHyOgEqMvHq8agButs6QILmqy0hvH9jEiwsF6k6a8l3bUTfnCCgTYfZzS/VQCkZJ+hPJk+Me36VQ1Z8d36ree7LJqBKRing2AJDiiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
